# Generated by Django 5.1.15 on 2026-10-06 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('code', models.CharField(help_text='Short operator code like APX, HZN, VLV', max_length=20, unique=True)),
                ('logo_url', models.URLField(blank=True, max_length=500)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=30)),
                ('website', models.URLField(blank=True)),
                ('rating', models.DecimalField(decimal_places=2, default=4.8, max_digits=3)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('is_verified', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('cancellation_policy', models.TextField(default='Full refund if cancelled 24+ hours before departure. 50% refund if cancelled 12-24 hours before. No refund within 12 hours of departure.')),
                ('terms_and_conditions', models.TextField(default='Passengers must present valid government ID matching the ticket name upon boarding. Arrive at terminal 30 minutes prior to departure.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-rating', 'name'],
                'indexes': [models.Index(fields=['slug'], name='operators_o_slug_a4e6c1_idx'), models.Index(fields=['is_active'], name='operators_o_is_acti_c0f0c5_idx'), models.Index(fields=['rating'], name='operators_o_rating_29d014_idx')],
            },
        ),
    ]
