# Generated by Django 5.1.15 on 2026-10-06 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_km', models.DecimalField(decimal_places=2, help_text='Total road/rail distance in km', max_digits=7)),
                ('estimated_duration_minutes', models.PositiveIntegerField(help_text='Estimated travel duration in minutes')),
                ('is_popular', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_destination', to='locations.city')),
                ('destination_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes_dest_station', to='locations.station')),
                ('origin_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_origin', to='locations.city')),
                ('origin_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes_origin_station', to='locations.station')),
            ],
            options={
                'ordering': ['origin_city', 'destination_city'],
                'indexes': [models.Index(fields=['origin_city', 'destination_city'], name='routes_rout_origin__3b9f8e_idx'), models.Index(fields=['is_popular'], name='routes_rout_is_popu_ee58ac_idx'), models.Index(fields=['is_active'], name='routes_rout_is_acti_d0dc30_idx')],
                'unique_together': {('origin_city', 'destination_city', 'origin_station', 'destination_station')},
            },
        ),
    ]
