# Generated by Django 5.1.15 on 2026-10-06 07:23

import apps.vehicles.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=50, unique=True)),
                ('vehicle_type', models.CharField(choices=[('BUS', 'Luxury Coach / Bus'), ('TRAIN', 'Express Train'), ('FLIGHT', 'Commercial Flight'), ('FERRY', 'High-Speed Ferry')], default='BUS', max_length=20)),
                ('model_name', models.CharField(max_length=150)),
                ('total_seats', models.PositiveIntegerField(default=40)),
                ('total_rows', models.PositiveIntegerField(default=10)),
                ('seats_per_row', models.PositiveIntegerField(default=4)),
                ('has_upper_deck', models.BooleanField(default=False)),
                ('amenities', models.JSONField(blank=True, default=apps.vehicles.models.default_amenities)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='operators.operator')),
            ],
            options={
                'ordering': ['operator', 'vehicle_number'],
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=10)),
                ('row', models.PositiveIntegerField()),
                ('column', models.PositiveIntegerField()),
                ('deck', models.CharField(choices=[('LOWER', 'Lower Deck / Main Floor'), ('UPPER', 'Upper Deck')], default='LOWER', max_length=10)),
                ('seat_type', models.CharField(choices=[('STANDARD', 'Standard'), ('WINDOW', 'Window Seat'), ('AISLE', 'Aisle Seat'), ('VIP', 'VIP / First Class'), ('SLEEPER', 'Sleeper Berth')], default='STANDARD', max_length=20)),
                ('is_accessible', models.BooleanField(default=False, help_text='Wheelchair / Special assistance accessible')),
                ('price_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('is_active', models.BooleanField(default=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['deck', 'row', 'column'],
            },
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['vehicle_number'], name='vehicles_ve_vehicle_f82abf_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['vehicle_type'], name='vehicles_ve_vehicle_76fbe4_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['is_active'], name='vehicles_ve_is_acti_53dbe5_idx'),
        ),
        migrations.AddIndex(
            model_name='seat',
            index=models.Index(fields=['vehicle', 'seat_number'], name='vehicles_se_vehicle_8768dc_idx'),
        ),
        migrations.AddIndex(
            model_name='seat',
            index=models.Index(fields=['seat_type'], name='vehicles_se_seat_ty_2d0aab_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('vehicle', 'seat_number', 'deck')},
        ),
    ]
