# Generated by Django 5.1.15 on 2026-10-06 07:23

import apps.tickets.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_code', models.CharField(default=apps.tickets.models.generate_ticket_code, max_length=64, unique=True)),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to='tickets/qr/')),
                ('qr_data', models.TextField(blank=True)),
                ('is_validated', models.BooleanField(default=False, help_text='True if scanned and validated at boarding gate')),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digital_tickets', to='bookings.booking')),
                ('passenger', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='digital_ticket', to='bookings.bookingpassenger')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ticket_code'], name='tickets_dig_ticket__6a36a7_idx'), models.Index(fields=['is_validated'], name='tickets_dig_is_vali_9c8b0e_idx')],
            },
        ),
    ]
